server:
    port: 8005

spring:
    datasource:
        url: jdbc:mysql://10.0.19.175:3306/javawebhomework?serverTimezone=CTT&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
    mvc:
        dispatch-options-request: true

# mybatis-plus配置
mybatis-plus:
    mapper-locations: classpath:mybatis/mapper/*.xml
    typeAliasesPackage: com.yyc.book.bean
    global-config:
        db-config:
            id-type: auto
            db-type: mysql
            field-strategy: not_null
        # mapper 自动刷新，调式使用
        refresh: true
        # mybatis 原生配置
    configuration:
        map-underscore-to-camel-case: true
        cache-enabled: false
        local-cache-scope: session
